### ISSUE TITLE
(Feature request) Mamba compatibility with PS3HEN

### ISSUE THREAD

**Issue by therevtanker2100** [aldostools/Mamba#7]
Alas I've attempted a stage2 payload from the .bin and it crashes HEN due to CFW compatibility only. Also I have a NOR flasher.

**Comment by aldostools** [comment]
The payloads are not interchangeable between them:
- HEN payload is for HEN.
- Cobra stage2 payload is for CFW. It's loaded by stage0.
- Mamba payload is for CFW. It's loaded by Cobra nocfw payload or by IRISMAN or Mamba loader.

Each payload has specific patches. Cobra/Mamba use LV1 patches that are not available on HEN.

**Comment by therevtanker2100** [comment]
> The payloads are not interchangeable between them:
> - HEN payload is for HEN.
> - Cobra stage2 payload is for CFW. It's loaded by stage0.
> - Mamba payload is for CFW. It's loaded by Cobra nocfw payload or by IRISMAN or Mamba loader.
> 
> Each payload has specific patches. Cobra/Mamba use LV1 patches that are not available on HEN.
> 
> 

Even though HEN uses Cobra would it still be possible for Mamba to be redone with lv2 limitations?

**Comment by aldostools** [comment]
HEN is based on Cobra payload. Same as Mamba.

It doesn't make sense using Mamba on HEN, since the 3 payloads are practically the "same" (each with their own limitations).

If there is a feature in Mamba that is not found in HEN, it only needs that someone port it to HEN (if it's allowed and don't require LV1 access).
